// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package gpc_dao

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetUsersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersRequest) Reset()         { *m = GetUsersRequest{} }
func (m *GetUsersRequest) String() string { return proto.CompactTextString(m) }
func (*GetUsersRequest) ProtoMessage()    {}
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *GetUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersRequest.Unmarshal(m, b)
}
func (m *GetUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersRequest.Marshal(b, m, deterministic)
}
func (m *GetUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersRequest.Merge(m, src)
}
func (m *GetUsersRequest) XXX_Size() int {
	return xxx_messageInfo_GetUsersRequest.Size(m)
}
func (m *GetUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersRequest proto.InternalMessageInfo

type GetUserByIdRequest struct {
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByIdRequest) Reset()         { *m = GetUserByIdRequest{} }
func (m *GetUserByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserByIdRequest) ProtoMessage()    {}
func (*GetUserByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *GetUserByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByIdRequest.Unmarshal(m, b)
}
func (m *GetUserByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByIdRequest.Marshal(b, m, deterministic)
}
func (m *GetUserByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByIdRequest.Merge(m, src)
}
func (m *GetUserByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserByIdRequest.Size(m)
}
func (m *GetUserByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByIdRequest proto.InternalMessageInfo

func (m *GetUserByIdRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type AddUserRequest struct {
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserRequest) Reset()         { *m = AddUserRequest{} }
func (m *AddUserRequest) String() string { return proto.CompactTextString(m) }
func (*AddUserRequest) ProtoMessage()    {}
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *AddUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserRequest.Unmarshal(m, b)
}
func (m *AddUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserRequest.Marshal(b, m, deterministic)
}
func (m *AddUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserRequest.Merge(m, src)
}
func (m *AddUserRequest) XXX_Size() int {
	return xxx_messageInfo_AddUserRequest.Size(m)
}
func (m *AddUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserRequest proto.InternalMessageInfo

func (m *AddUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRequest struct {
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteUserRequest struct {
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type ExecSQLResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	LastInsertId         int32    `protobuf:"varint,2,opt,name=lastInsertId,proto3" json:"lastInsertId,omitempty"`
	AffectRows           int32    `protobuf:"varint,3,opt,name=affectRows,proto3" json:"affectRows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecSQLResponse) Reset()         { *m = ExecSQLResponse{} }
func (m *ExecSQLResponse) String() string { return proto.CompactTextString(m) }
func (*ExecSQLResponse) ProtoMessage()    {}
func (*ExecSQLResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *ExecSQLResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecSQLResponse.Unmarshal(m, b)
}
func (m *ExecSQLResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecSQLResponse.Marshal(b, m, deterministic)
}
func (m *ExecSQLResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecSQLResponse.Merge(m, src)
}
func (m *ExecSQLResponse) XXX_Size() int {
	return xxx_messageInfo_ExecSQLResponse.Size(m)
}
func (m *ExecSQLResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecSQLResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecSQLResponse proto.InternalMessageInfo

func (m *ExecSQLResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ExecSQLResponse) GetLastInsertId() int32 {
	if m != nil {
		return m.LastInsertId
	}
	return 0
}

func (m *ExecSQLResponse) GetAffectRows() int32 {
	if m != nil {
		return m.AffectRows
	}
	return 0
}

type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*GetUsersRequest)(nil), "rpc_dao.GetUsersRequest")
	proto.RegisterType((*GetUserByIdRequest)(nil), "rpc_dao.GetUserByIdRequest")
	proto.RegisterType((*AddUserRequest)(nil), "rpc_dao.AddUserRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "rpc_dao.UpdateUserRequest")
	proto.RegisterType((*DeleteUserRequest)(nil), "rpc_dao.DeleteUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "rpc_dao.GetUserResponse")
	proto.RegisterType((*ExecSQLResponse)(nil), "rpc_dao.ExecSQLResponse")
	proto.RegisterType((*User)(nil), "rpc_dao.User")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x41, 0x4f, 0xf2, 0x40,
	0x10, 0xa5, 0xa5, 0x7c, 0xfd, 0x18, 0x14, 0x64, 0x62, 0x62, 0x83, 0x89, 0xd1, 0xd5, 0x83, 0x27,
	0x62, 0xc0, 0x78, 0x34, 0x81, 0xa0, 0x86, 0xc4, 0xc4, 0xb8, 0x86, 0x8b, 0x17, 0xb3, 0xb2, 0x03,
	0x21, 0x01, 0x5a, 0xbb, 0x4b, 0xd4, 0x1f, 0xeb, 0x7f, 0x31, 0x5d, 0xda, 0x52, 0x4a, 0xc4, 0x78,
	0xeb, 0xce, 0xbc, 0xf7, 0x66, 0x26, 0xef, 0x15, 0x60, 0xa1, 0x28, 0x6c, 0x06, 0xa1, 0xaf, 0x7d,
	0x74, 0xc3, 0x60, 0xf8, 0x22, 0x85, 0xcf, 0xea, 0x50, 0xbb, 0x23, 0x3d, 0x50, 0x14, 0x2a, 0x4e,
	0x6f, 0x0b, 0x52, 0x9a, 0x9d, 0x01, 0xc6, 0xa5, 0xee, 0x67, 0x5f, 0xc6, 0x55, 0xac, 0x82, 0x3d,
	0x91, 0x9e, 0x7d, 0x6c, 0x9d, 0x97, 0xb8, 0x3d, 0x91, 0xac, 0x0d, 0xd5, 0x8e, 0x94, 0x11, 0x2a,
	0x41, 0x9c, 0x80, 0x13, 0x4d, 0x30, 0x98, 0x4a, 0x6b, 0xb7, 0x19, 0x8f, 0x68, 0x1a, 0x8c, 0x69,
	0xb1, 0x2b, 0xa8, 0x0f, 0x02, 0x29, 0x34, 0xfd, 0x91, 0x77, 0x0a, 0xf5, 0x1e, 0x4d, 0x69, 0x9d,
	0x97, 0xdf, 0xe8, 0x32, 0x3d, 0x85, 0x93, 0x0a, 0xfc, 0xb9, 0xa2, 0x54, 0xda, 0xfa, 0x59, 0xda,
	0x87, 0xda, 0xcd, 0x07, 0x0d, 0x9f, 0x1e, 0xef, 0x53, 0x96, 0x07, 0xee, 0x8c, 0x94, 0x12, 0x63,
	0x32, 0xc4, 0x32, 0x4f, 0x9e, 0xc8, 0x60, 0x67, 0x2a, 0x94, 0xee, 0xcf, 0x15, 0x85, 0xba, 0x9f,
	0x0c, 0x5f, 0xab, 0xe1, 0x11, 0x80, 0x18, 0x8d, 0x68, 0xa8, 0xb9, 0xff, 0xae, 0xbc, 0xa2, 0x41,
	0x64, 0x2a, 0x8c, 0x83, 0x13, 0x8d, 0x8f, 0xd7, 0xb7, 0x92, 0xf5, 0x11, 0xc1, 0x99, 0x8b, 0x19,
	0x19, 0xcd, 0x32, 0x37, 0xdf, 0xb8, 0x07, 0xc5, 0x68, 0x8b, 0xa5, 0x48, 0xf4, 0x89, 0xfb, 0x50,
	0xa2, 0x99, 0x98, 0x4c, 0x3d, 0xc7, 0xc0, 0x96, 0x8f, 0xd6, 0x97, 0x0d, 0xc5, 0x5e, 0xe7, 0x01,
	0xbb, 0xf0, 0x3f, 0x71, 0x13, 0xbd, 0xf4, 0xda, 0x9c, 0xc1, 0x8d, 0x8d, 0x4e, 0x72, 0x39, 0x2b,
	0x5c, 0x58, 0x78, 0x0b, 0x95, 0x8c, 0xfd, 0x78, 0x98, 0x07, 0x67, 0x42, 0xb1, 0x4d, 0x09, 0xaf,
	0xc1, 0x8d, 0x03, 0x82, 0x07, 0x29, 0x6c, 0x3d, 0x32, 0x19, 0x7e, 0xce, 0x03, 0x56, 0xc0, 0x1e,
	0xc0, 0x2a, 0x2b, 0xd8, 0x58, 0x79, 0x97, 0x0f, 0xd0, 0x6f, 0x2a, 0xab, 0xe4, 0x64, 0x54, 0x36,
	0xe2, 0xb4, 0x4d, 0xa5, 0x5b, 0x7e, 0x76, 0xc7, 0xcb, 0xe6, 0xeb, 0x3f, 0xf3, 0x03, 0xb5, 0xbf,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x52, 0x0a, 0xea, 0x4e, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DAOClient is the client API for DAO service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DAOClient interface {
	GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (DAO_GetUsersClient, error)
	GetUserById(ctx context.Context, in *GetUserByIdRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*ExecSQLResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*ExecSQLResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*ExecSQLResponse, error)
}

type dAOClient struct {
	cc grpc.ClientConnInterface
}

func NewDAOClient(cc grpc.ClientConnInterface) DAOClient {
	return &dAOClient{cc}
}

func (c *dAOClient) GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (DAO_GetUsersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DAO_serviceDesc.Streams[0], "/rpc_dao.DAO/GetUsers", opts...)
	if err != nil {
		return nil, err
	}
	x := &dAOGetUsersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DAO_GetUsersClient interface {
	Recv() (*GetUserResponse, error)
	grpc.ClientStream
}

type dAOGetUsersClient struct {
	grpc.ClientStream
}

func (x *dAOGetUsersClient) Recv() (*GetUserResponse, error) {
	m := new(GetUserResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dAOClient) GetUserById(ctx context.Context, in *GetUserByIdRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/rpc_dao.DAO/GetUserById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAOClient) AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*ExecSQLResponse, error) {
	out := new(ExecSQLResponse)
	err := c.cc.Invoke(ctx, "/rpc_dao.DAO/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAOClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*ExecSQLResponse, error) {
	out := new(ExecSQLResponse)
	err := c.cc.Invoke(ctx, "/rpc_dao.DAO/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAOClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*ExecSQLResponse, error) {
	out := new(ExecSQLResponse)
	err := c.cc.Invoke(ctx, "/rpc_dao.DAO/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DAOServer is the server API for DAO service.
type DAOServer interface {
	GetUsers(*GetUsersRequest, DAO_GetUsersServer) error
	GetUserById(context.Context, *GetUserByIdRequest) (*GetUserResponse, error)
	AddUser(context.Context, *AddUserRequest) (*ExecSQLResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*ExecSQLResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*ExecSQLResponse, error)
}

// UnimplementedDAOServer can be embedded to have forward compatible implementations.
type UnimplementedDAOServer struct {
}

func (*UnimplementedDAOServer) GetUsers(req *GetUsersRequest, srv DAO_GetUsersServer) error {
	return status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (*UnimplementedDAOServer) GetUserById(ctx context.Context, req *GetUserByIdRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserById not implemented")
}
func (*UnimplementedDAOServer) AddUser(ctx context.Context, req *AddUserRequest) (*ExecSQLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUser not implemented")
}
func (*UnimplementedDAOServer) UpdateUser(ctx context.Context, req *UpdateUserRequest) (*ExecSQLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedDAOServer) DeleteUser(ctx context.Context, req *DeleteUserRequest) (*ExecSQLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}

func RegisterDAOServer(s *grpc.Server, srv DAOServer) {
	s.RegisterService(&_DAO_serviceDesc, srv)
}

func _DAO_GetUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetUsersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DAOServer).GetUsers(m, &dAOGetUsersServer{stream})
}

type DAO_GetUsersServer interface {
	Send(*GetUserResponse) error
	grpc.ServerStream
}

type dAOGetUsersServer struct {
	grpc.ServerStream
}

func (x *dAOGetUsersServer) Send(m *GetUserResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _DAO_GetUserById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAOServer).GetUserById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_dao.DAO/GetUserById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAOServer).GetUserById(ctx, req.(*GetUserByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAO_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAOServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_dao.DAO/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAOServer).AddUser(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAO_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAOServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_dao.DAO/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAOServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DAO_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAOServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_dao.DAO/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAOServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DAO_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc_dao.DAO",
	HandlerType: (*DAOServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserById",
			Handler:    _DAO_GetUserById_Handler,
		},
		{
			MethodName: "AddUser",
			Handler:    _DAO_AddUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _DAO_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _DAO_DeleteUser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetUsers",
			Handler:       _DAO_GetUsers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "user.proto",
}
